;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="RobotArm.CombinePhase.Left",NewTagName="RobotArm.CombinePhase.Front")
+GameplayTagRedirects=(OldTagName="RobotArm.CombinePhase.Right",NewTagName="RobotArm.CombinePhase.Back")
+GameplayTagList=(Tag="AGV.Phase.Flexible",DevComment="")
+GameplayTagList=(Tag="AGV.Phase.Idle",DevComment="")
+GameplayTagList=(Tag="AGV.Phase.Inspection",DevComment="")
+GameplayTagList=(Tag="AGV.Phase.Supply",DevComment="")
+GameplayTagList=(Tag="AGV.Phase.Trim",DevComment="")
+GameplayTagList=(Tag="Cell.State.Free",DevComment="")
+GameplayTagList=(Tag="Cell.State.Pending",DevComment="")
+GameplayTagList=(Tag="Cell.State.Working",DevComment="")
+GameplayTagList=(Tag="Cell.Type.Flexible",DevComment="")
+GameplayTagList=(Tag="Cell.Type.Inspection",DevComment="")
+GameplayTagList=(Tag="Cell.Type.Supply",DevComment="")
+GameplayTagList=(Tag="Cell.Type.Trim",DevComment="")
+GameplayTagList=(Tag="RobotArm.CombinePhase.Back",DevComment="")
+GameplayTagList=(Tag="RobotArm.CombinePhase.Front",DevComment="")
+GameplayTagList=(Tag="RobotArm.Type.Left",DevComment="")
+GameplayTagList=(Tag="RobotArm.Type.Right",DevComment="")
+GameplayTagList=(Tag="Tire.State.Combine",DevComment="")
+GameplayTagList=(Tag="Tire.State.None",DevComment="")

