// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace DFGameplayTags
{
	/* AGV Phase*/
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AGV_Phase_None);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AGV_Phase_Home);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AGV_Phase_Supply);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AGV_Phase_Flexible);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AGV_Phase_Trim);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AGV_Phase_Inspection);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AGV_Phase_Load);

	/* AGV State */
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AGV_State_Idle);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AGV_State_Move);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AGV_State_Return);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AGV_State_Work);

	/* Cell State */
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cell_State_Free);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cell_State_Pending);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cell_State_Working);

	/* Cell Type */
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cell_Type_Supply);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cell_Type_Flexible);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cell_Type_Trim);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cell_Type_Inspection);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cell_Type_Load);

	/* RobotArm CombinePhase */
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RobotArm_CombinePhase_Front);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RobotArm_CombinePhase_Back);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RobotArm_CombinePhase_Finish);

	/* RobotArm Type */
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RobotArm_Type_Left);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RobotArm_Type_Right);

	/* Tire State */
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tire_State_Combine);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tire_State_None);

	/* Vehicle */
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vehicle_Tire_Back_Left);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vehicle_Tire_Back_Right);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vehicle_Tire_Front_Left);
	DIGITALFACTORY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vehicle_Tire_Front_Right);
}